version: '3.3'
services:
  application: 
    image: user-service
    restart: always
    build: .
    ports:
     - "8080:8080"
    environment:
      - MYSQL_HOST= mysqldb
      - MYSQL_ROOT_USER= dockeruser
      - MYSQL_ROOT_PASSWORD=khan1234
      - MYSQL_DATABASE=registration
      - MYSQL_PORT=3306

  mysqldb:
    image: mysql  
    restart: always
    environment:
      - MYSQL_ROOT_USER= dockeruser
      - MYSQL_ROOT_PASSWORD=khan1234
      - MYSQL_DATABASE=registration
    ports:
     - "3307:3306" 
    expose:
     - '3306' 
    volumes:
     - my-db:/var/lib/mysql

volumes:
   my-db:      
   
